// Thumbnail + title audit (improvement_plan.md Phase 18).
//
// The plan's instruction is "verify against the generated corpus rather than
// assuming", so everything below is computed from the 93 generated scripts.
//
//   node scripts/thumb-audit.mjs                -> qa/THUMBNAIL.md
//   node scripts/thumb-audit.mjs --out=-        print instead
//
// No dev server, no ffmpeg: the thumbnail's own geometry is arithmetic, and the
// corpus is JSON.
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const OUT = (args.find((a) => a.startsWith("--out=")) ?? "--out=qa/THUMBNAIL.md").slice(6);

/* The real YouTube feed thumbnail is 168x94 CSS px; the generator renders 1280x720
 * (`thumbnail.ts:16-17`), so everything shrinks by this factor. */
const FEED_W = 168;
const FEED_H = 94;
const THUMB_H = 720;
const FEED_SCALE = FEED_H / THUMB_H;
const UNIT = THUMB_H / 24;

/* Every text element the generator draws, with the `unit` multiple it uses and
 * where. Kept here rather than imported because `thumbnail.ts` pulls in
 * `painters/common`, which is browser-only. */
const TEXT_ELEMENTS = [
  { name: "headline, largest start size", unitMul: 4.6, src: "thumbnail.ts:139" },
  { name: "headline, smallest allowed", unitMul: 2.0, src: "thumbnail.ts:118" },
  { name: "category pill", unitMul: 1.0, src: "thumbnail.ts:78,134" },
  { name: "brand line", unitMul: 0.95, src: "thumbnail.ts:174" },
  { name: "subject label (variant 2)", unitMul: 0.85, src: "thumbnail.ts:110" },
];

/* Below this, text in a feed thumbnail is texture rather than words. */
const LEGIBLE_PX = 8;
/* The plan's own guideline for a scannable thumbnail. */
const MAX_HEADLINE_WORDS = 4;

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(full)));
    else if (e.isFile() && e.name.endsWith(".json")) out.push(full);
  }
  return out;
}

async function corpus() {
  const out = [];
  for (const f of await walk(path.join(ROOT, "content/factory"))) {
    if (path.basename(f) === "directives.json") continue;
    try {
      const s = JSON.parse(await readFile(f, "utf8"))?.script;
      if (Array.isArray(s?.scenes) && s.topic) out.push(s);
    } catch {
      /* unparseable slot */
    }
  }
  for (const f of await walk(path.join(ROOT, "content/videos"))) {
    if (path.basename(f) !== "script.json") continue;
    try {
      const s = JSON.parse(await readFile(f, "utf8"));
      if (Array.isArray(s?.scenes) && s.topic) out.push(s);
    } catch {
      /* unparseable slot */
    }
  }
  return out;
}

const words = (s) => s.trim().split(/\s+/).filter(Boolean);
/** Same headline the generator draws: `topic.split(":")[0]` (thumbnail.ts:73). */
const headlineOf = (s) => s.topic.split(":")[0].trim();
const contentWords = (t) =>
  t.toLowerCase().replace(/#\w+/g, "").replace(/[^a-z0-9 ]/g, " ").split(/\s+/).filter((w) => w.length > 2);

function pct(list, p) {
  const a = [...list].sort((x, y) => x - y);
  return a[Math.min(a.length - 1, Math.ceil((p / 100) * a.length) - 1)];
}

const scripts = await corpus();
const heads = scripts.map(headlineOf);
const headWords = heads.map((h) => words(h).length);
const overLong = headWords.filter((n) => n > MAX_HEADLINE_WORDS).length;

const withTitle = scripts.filter((s) => s.meta?.title);
const titleLens = withTitle.map((s) => s.meta.title.length);
const shorts = withTitle.filter((s) => s.format === "short");
const taggedShorts = shorts.filter((s) => /#shorts\s*$/i.test(s.meta.title)).length;
const truncated = titleLens.filter((n) => n > 70).length;
const echoes = withTitle.filter((s) => {
  const head = new Set(contentWords(headlineOf(s)));
  const title = new Set(contentWords(s.meta.title));
  if (!head.size) return false;
  return [...head].filter((w) => title.has(w)).length / head.size >= 0.8;
}).length;

const L = [];
L.push("# Thumbnail & title audit");
L.push("");
L.push("Generated by `node scripts/thumb-audit.mjs`. **Do not hand-edit.**");
L.push("");
L.push(`Corpus: **${scripts.length} scripts**, ${withTitle.length} with generated \`meta.title\`.`);
L.push("");
L.push("## 1. Legibility at real feed size");
L.push("");
L.push(
  `The generator renders ${THUMB_H * (16 / 9)}×${THUMB_H} (\`thumbnail.ts:16-17\`); a YouTube feed card is ` +
    `${FEED_W}×${FEED_H}, so every size is multiplied by **${FEED_SCALE.toFixed(3)}**. ` +
    `Under ~${LEGIBLE_PX} px, text is texture rather than words.`
);
L.push("");
L.push("| Element | Rendered px | At 168×94 | Legible? | Source |");
L.push("|---|---|---|---|---|");
for (const e of TEXT_ELEMENTS) {
  const rendered = UNIT * e.unitMul;
  const feed = rendered * FEED_SCALE;
  L.push(
    `| ${e.name} | ${rendered.toFixed(0)} | **${feed.toFixed(1)}** | ${feed >= LEGIBLE_PX ? "yes" : "**no**"} | \`${e.src}\` |`
  );
}
L.push("");
L.push(
  "So only the headline survives the feed. The category pill, the brand line and variant 2's subject " +
    "label are all under 4 px — they are decoration at full size and noise at feed size."
);
L.push("");
L.push("## 2. Headline length");
L.push("");
L.push(
  `The headline is \`topic.split(":")[0]\` and wraps to at most 3 lines. Guideline is ` +
    `≤ ${MAX_HEADLINE_WORDS} words.`
);
L.push("");
L.push(`| Words | p10 | p50 | p90 | max |`);
L.push(`|---|---|---|---|---|`);
L.push(
  `| headline | ${pct(headWords, 10)} | **${pct(headWords, 50)}** | ${pct(headWords, 90)} | ${pct(headWords, 100)} |`
);
L.push("");
L.push(
  `**${overLong} of ${headWords.length} (${((overLong / headWords.length) * 100).toFixed(0)}%) exceed ` +
    `${MAX_HEADLINE_WORDS} words.** A 12-word headline wraps to 3 lines and drops toward the ${(UNIT * 2.0 * FEED_SCALE).toFixed(1)} px floor.`
);
L.push("");
L.push("Longest in the corpus:");
L.push("");
for (const h of [...heads].sort((a, b) => words(b).length - words(a).length).slice(0, 5)) {
  L.push(`- ${words(h).length}w — ${h}`);
}
L.push("");
L.push("## 3. Does the thumbnail complement the title, or repeat it?");
L.push("");
L.push(
  `**${echoes} of ${withTitle.length} (${((echoes / withTitle.length) * 100).toFixed(0)}%)** have a headline ` +
    `whose content words are ≥80% contained in the title. Those cards spend the viewer's only glance ` +
    `restating text that is already printed underneath them.`
);
L.push("");
L.push("## 4. Titles — the part that is already fine");
L.push("");
L.push("| Metric | Value | Prompt asks |");
L.push("|---|---|---|");
L.push(`| Title chars p10/p50/p90/max | ${pct(titleLens, 10)} / **${pct(titleLens, 50)}** / ${pct(titleLens, 90)} / ${pct(titleLens, 100)} | 35-90 long, 35-70 short |`);
L.push(`| Over 70 chars (feed truncation) | ${truncated} of ${titleLens.length} | few |`);
L.push(`| Shorts ending in \`#Shorts\` | ${taggedShorts} of ${shorts.length} | all |`);
L.push("");
L.push(
  "This is a negative result and worth recording as one: the plan flagged titles as unverified, and " +
    "measured, they follow the prompt. The thumbnail is where the work is."
);

const report = `${L.join("\n")}\n`;
if (OUT === "-") {
  console.log(report);
} else {
  await mkdir(path.join(ROOT, path.dirname(OUT)), { recursive: true });
  await writeFile(path.join(ROOT, OUT), report);
  console.log(`wrote ${OUT}`);
}
